### ISSUE TITLE
[Feat] 휴지통 기능 구현

### ISSUE THREAD

**Issue by qwwx99** [tjdckscert/ood03#11]
## 📝 Description
- 휴지통 기능 구현

## 📍 Todo
- [] 메일함 삭제할때 경고(알림)으로 한번더 묻기 구현
- [] 휴지통 페이지 구현
- [] 사용자가 메일을 삭제를 누르면 메일함에서 해당 메일이 삭제 후 휴지통으로 이동 구현
- [] 메일함에서 삭제하면 mysql의 trash테이블에 저장
- [] 휴지통 이동시 해당 사용자 아이디에 맞는 휴지통 메일이 표시
- [] 휴지통에서 삭제 시 영구적으로 삭제 기능 구현
- [] 휴지통에서 메일 이름 클릭시 해당 메일 보기 기능 구현
- [] 휴지통에서 복구 시 해당 메일을 메일함으로 복구 기능 구현
