### ISSUE TITLE
[Feat] 완전화 유지보수에 필요한 기능 구현

### ISSUE THREAD

**Issue by tjdckscert** [tjdckscert/ood03#5]
## 📝 Description
- 완전화 유지보수에 필요한 기능 구현

## 📍 Todo
- [ ] 메일 읽음 기능 구현
- [ ] 페이징 기능 구현
- [ ] 카테고리 기능 구현
- [ ] 메일 작성 시 글자 수 제한 기능 구현
